CREATE TABLE users  (
    code BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    login VARCHAR(15) NOT NULL UNIQUE,
    password VARCHAR(30) NOT NULL,
    role VARCHAR(10) NOT NULL
);
